### ISSUE TITLE
Fresh install of SECP256K1 compiles to .cpp.o while the compiler looks for .c.o.

### ISSUE THREAD

**Issue by kayabaNerve** [EmberCrypto/Ember#10]
The current fix is to compile for C before compiling for C++, and not clear the cache.

This is likely a problem with Status's lib, not Ember, but I don't know yet and Ember's the one who's showing the problem.

**Comment by Mistersx12** [comment]
Ok. Thank you for update!

**Comment by mrmetech** [comment]
`CC: Test
CC: stdlib_system
CC: stdlib_sharedlist
CC: stdlib_locks
CC: libTest
CC: BaseTest
CC: Base16Test
CC: BN_BN
CC: Base
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Isrc/lib/Hash/Argon/include -Isrc/lib/Hash/Argon/src/blake2 -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1 -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -g3 -O0 -gdwarf-3 -Os  -IC:\Users\Kolby\.choosenim\toolchains\nim-#devel\lib -o C:\Users\Kolby\Documents\GitHub\Ember\build\nimcache\secp256k1.c.o C:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src/secp256k1.c' failed with exit code: 1

gcc.exe: error: C:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src/secp256k1.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.`

**Comment by mrmetech** [comment]
```
CC: Test
CC: stdlib_system
CC: stdlib_sharedlist
CC: stdlib_locks
CC: libTest
CC: BaseTest
CC: Base16Test
CC: BN_BN
CC: Base
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Isrc/lib/Hash/Argon/include -Isrc/lib/Hash/Argon/src/blake2 -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1 -IC:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -g3 -O0 -gdwarf-3 -Os  -IC:\Users\Kolby\.choosenim\toolchains\nim-#devel\lib -o C:\Users\Kolby\Documents\GitHub\Ember\build\nimcache\secp256k1.c.o C:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src/secp256k1.c' failed with exit code: 1

gcc.exe: error: C:\Users\Kolby\.nimble\pkgs\secp256k1-0.1.0/secp256k1_wrapper/secp256k1/src/secp256k1.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
```

**Comment by kayabaNerve** [comment]
Nope. That's a different error from you not having installed it correctly.
