### ISSUE TITLE
Invalid data packets can abort the node on the listening port.

### ISSUE THREAD

**Issue by rpgoldberg** [EmberCrypto/Ember#37]
If you check the port status from https://www.yougetsignal.com/tools/open-ports/ to the listening port of the node (say 5132), it will cause the node to fail and terminate.

**Comment by kayabaNerve** [comment]
This is likely in the Handshake (I doubt a random packet could handshake successfully)... Honestly, I'm guessing it's some nil error when it tries to read data that doesn't exist.
